version: "3.8"

services:
  mongo:
    image: mongo:6.0
    container_name: portfolio-mongo
    restart: unless-stopped
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db
    env_file:
      - .env

  backend:
    build:
      context: .
      dockerfile: backend/Dockerfile
    container_name: portfolio-backend
    restart: unless-stopped
    ports:
      - "5000:5000"
    depends_on:
      - mongo
    env_file:
      - ./backend/.env

  frontend:
    build:
      context: .
      dockerfile: frontend/Dockerfile
    container_name: portfolio-frontend
    restart: unless-stopped
    ports:
      - "3000:3000"
    depends_on:
      - backend
    env_file:
      - ./frontend/.env.local

volumes:
  mongo-data:
